### ISSUE TITLE
Question about srx files

### ISSUE THREAD

**Issue by matanox** [loomchild/segment#12]
Does this repo come with any recommended srx files for English?
I've not been lucky finding ready-made ones, which are known to work in general well. Thanks in advance for commenting!

**Comment by janissl** [comment]
You can try the SRX file from the [languagetool-org](https://github.com/languagetool-org/languagetool/tree/master/languagetool-core/src/main/resources/org/languagetool/resource) project. It works quite well.

**Comment by matanox** [comment]
@janissl thanks a lot, I was never sure where to find good srx files. I think the author of this library @loomchild also wrote a thesis about this task, but not sure to find it. Would also by any chance be able to recommend some additional stable library for running SRX files with solid stability and good performance on huge files?

**Comment by loomchild** [comment]
Hi, yeah, I was always using Language Tool SRX files. I was also working on some commercial SRX files long time ago, but I believe they were worse and eventually converged. 

As for my master's thesis you can find it here: https://loomchild.net/files/2013/12/Urownoleglanie_Tekstow_Dwujezycznych.pdf. Unfortunately it's written in Polish, so it might not be of much use. Also the subject is bilingual text alignment at sentence level using TMX and sentence splitting is only a part of it.

I have also co-written a paper with Marcin Milkowski about segmentation: https://loomchild.net/files/2013/12/Using_SRX_standard_for_sentence_segmentation_in_LanguageTool.pdf. This one is in English and might be of more use, including references. However, it was a couple of years ago as well.

As for another SRX library, I currently don't know any at the moment (since I haven't worked on this subject professionally for a while), but I am sure they appeared over the years. I remember I wanted to integrate `maligna` with Okapi Framework at some point, which contains some support for SRX as far as I remember, but never actually did it. 

Could you share what issues do you encounter with `segment`? I always thought performance is relatively good and it can handle large files without using too much memory thanks to streaming implementation. However, I am always interested in improving it.

**Comment by janissl** [comment]
@loomchild Thanks for sharing. These papers will help to understand better your idea behind the segment tool. For me as former translator, it is not a big problem to read even in Polish. It will just take additional time but is feasible in the end. :)

**Comment by matanox** [comment]
@janissl maybe you'd post a super brief summary here if you ever do :)

**Comment by matanox** [comment]
@loomchild no issues at all, I was just hesitant using it given there were just two commits in the past two years, but I think I am going to!

**Comment by loomchild** [comment]
Heh, I guess it sort of does the job, so I didn't need to make any changes recently. The SRX standard was also last updated in 2008, so it's not evolving much. I assure you that the library is still maintained, I am available to accept pull requests / fix bugs.

**Comment by matanox** [comment]
Hey, thanks for this, and also the help on the other thread!!
Good libraries simply don't require more changes :-)
