### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by matanox** [loomchild/segment#13]
Actually it's not straightforward how to run the `segment` script which is mentioned in the readme. There's certainly no bin directory after `mvn clean install`.

**Comment by loomchild** [comment]
It's in target/segment-[version].zip package when you run maven in segment-ui directory. You need to unpack it in order to use it. This project was mostly thought as a library - if you just want to use it as a tool, then feel free to download the last binary distribution: https://github.com/loomchild/segment/releases/download/2.0.0/segment-2.0.0.zip

I will clarify that in README.

**Comment by matanox** [comment]
I'd actually be thrilled using it as both!

Wasn't sure till now, that the library option is also equally available.
Some other people structure their code exclusively only around a tool, but
obviously you did it the right way :-)

Huge thanks!

**Comment by loomchild** [comment]
Me pleasure:)

The library code is in [/segment](https://github.com/loomchild/segment/tree/master/segment) directory. You can also download it directly from [Maven central](http://search.maven.org/#search%7Cga%7C1%7Cnet.loomchild.segment). 

For usage look into [SrxAnyParser](https://github.com/loomchild/segment/blob/master/segment/src/main/java/net/loomchild/segment/srx/io/SrxAnyParser.java) to produce SrxDocument class and into [SrxTextIterator](https://github.com/loomchild/segment/blob/master/segment/src/main/java/net/loomchild/segment/srx/SrxTextIterator.java) class to segment the text (sorry, no clear README). Also check how LanguageTool uses it.
